GET http://127.0.0.1:3001/contactos/1 HTTP/1.1
content-type: application/json

###
GET http://127.0.0.1:3001/contactos HTTP/1.1
content-type: application/json

###
POST http://127.0.0.1:3001/contactos HTTP/1.1
content-type: application/json

{
    "date":123,
    "favourite":123,
    "name":123,
    "phone":123
}

###

PUT http://127.0.0.1:3001/contactos HTTP/1.1
content-type: application/json

{
    "id": 2,
    "date":123,
    "favourite":"hola buenos dias",
    "name":123,
    "phone":123
}
