## Get all contacts
GET http://127.0.0.1:3001/contact/ HTTP/1.1 
content-type: application/json

### Get favourites contacts
GET http://localhost:3001/contact/favourites HTTP/1.1 
content-type: application/json

### Get one contact
GET http://localhost:3001/contact/1 HTTP/1.1 
content-type: application/json

### Search contact by name from the body
GET http://localhost:3001/contact/search_name HTTP/1.1 
content-type: application/json

{
"name":"Alfredo"
}

### Search contact by lastname from the body
GET http://localhost:3001/contact/search_lastname HTTP/1.1 
content-type: application/json

{
    "lastname":"Juan"
}

### Create contact
POST http://localhost:3001/contact/ HTTP/1.1 
content-type: application/json

{
    "name":"Alesi",
    "lastname": "Peralta",
    "phone":"154299666",
    "favourite":true
}

### Update contact
PUT http://localhost:3001/contact/1 HTTP/1.1 
content-type: application/json

{
    "name":"Ismael",
    "lastname":"Rodriguez",
    "phone":"0855599924458"
}

### Delete contact
DELETE http://localhost:3003/contact/2 HTTP/1.1 
content-type: application/json