### OBTENER TODOS LOS USUARIOS
GET http://127.0.0.1:3001/user HTTP/1.1
content-type: application/json

### OBTENER UN USUARIO
GET http://127.0.0.1:3001/user/7 HTTP/1.1
content-type: application/json

### AGREGAR UN USUARIO
POST http://127.0.0.1:3001/user HTTP/1.1
content-type: application/json
adminpassword: admin

{
    "name": "Tadeo",
    "email": "Tadeo@gmail.com",
    "password": "tadeo"
}

### EDITAR UN USUARIO
PUT http://127.0.0.1:3001/user/1 HTTP/1.1
content-type: application/json

{
    "name": "Tadeo",
    "email": "Tadeo@gmail.com",
    "password": "tadeo"
}

### BORRAR UN USUARIO
DELETE http://127.0.0.1:3001/user/1 HTTP/1.1
content-type: application/json
