### OBTENER TODOS LOS USUARIOS
GET http://127.0.0.1:3001/user HTTP/1.1
content-type: application/json

### OBTENER UN USUARIO
GET http://127.0.0.1:3001/user/2 HTTP/1.1
content-type: application/json

### AGREGAR UN USUARIO
POST http://127.0.0.1:3001/user HTTP/1.1
content-type: application/json
adminPassword: a

{
    "name": "asdwfw",
    "email": "admin@gmail.com",
    "password": "admin"
}

### EDITAR UN USUARIO
PUT http://127.0.0.1:3001/user/2 HTTP/1.1
content-type: application/json

{
    "name": "Javier",
    "email": "Javier@gmail.com",
    "password": "2989898"
}

### BORRAR UN USUARIO
DELETE http://127.0.0.1:3001/user/1 HTTP/1.1
content-type: application/json
